### ISSUE TITLE
Registry Review v0.4.0

### ISSUE THREAD

**Issue by ngokevin** [chenzlabs/auto-detect-controllers#1]
**Required:**

- [x] gearvr-controls wasn't part of core now. The documentation should suggest where to grab that, and a code example of including it.
- [x] Screenshot (some images of controllers would do)
- [x] Add a small bit of explanation in the README on why you'd want to use `trackedcontrols`. Maybe `noModel` prop name might be clearer? Also a bit confusing having `trackedcontrols: false` in the example, but the table says the property defaults to `true`

**Comment by machenmusik** [comment]
thanks!
